//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace csv_test
{
    using System;
    using System.Collections.Generic;
    
    public partial class AstronomyEntry
    {
        public int IDEntry { get; set; }
        public Nullable<int> Hip { get; set; }
        public Nullable<int> Hd { get; set; }
        public Nullable<int> Hr { get; set; }
        public Nullable<int> Gl { get; set; }
        public Nullable<int> Bf { get; set; }
        public string Proper { get; set; }
        public Nullable<int> Ra { get; set; }
        public Nullable<int> Dec { get; set; }
        public Nullable<decimal> Dist { get; set; }
        public Nullable<decimal> Pmra { get; set; }
        public Nullable<decimal> Pmdec { get; set; }
        public Nullable<decimal> Rv { get; set; }
        public Nullable<decimal> Mag { get; set; }
        public Nullable<decimal> Absmag { get; set; }
        public string Spect { get; set; }
        public Nullable<decimal> Ci { get; set; }
        public Nullable<decimal> X { get; set; }
        public Nullable<decimal> Y { get; set; }
        public Nullable<decimal> Z { get; set; }
        public Nullable<decimal> Vx { get; set; }
        public Nullable<decimal> Vy { get; set; }
        public Nullable<decimal> Vz { get; set; }
        public Nullable<decimal> Rrad { get; set; }
        public Nullable<decimal> Decrad { get; set; }
        public Nullable<decimal> Pmrarad { get; set; }
        public Nullable<decimal> Pmdecrad { get; set; }
        public string Bayer { get; set; }
        public Nullable<int> Flam { get; set; }
        public string Con { get; set; }
        public Nullable<int> Comp { get; set; }
        public Nullable<int> Comp_primary { get; set; }
        public string Base { get; set; }
        public Nullable<decimal> Lum { get; set; }
        public string Var { get; set; }
        public Nullable<decimal> Var_min { get; set; }
        public Nullable<decimal> Var_max { get; set; }
        public string Name { get; set; }
    }
}
